### PR TITLE
Fix/compose

### LINKED ISSUE #140: Allow frontend to use runtime ENVIRONMENT variables
the docker container as it is right now need the URLs and other configurable data to be passed in at build time.

We need the "compiled" frontend app to consume the environment variables that have been set at runtime in the container. 

either nginx or node runtime is acceptable for the runtime container. 
the frontend image will contain only the `build` folder of the frontend app not all the sourcecode.

### PR DESCRIPTION
**Pull request by bvizureanu**
### Requirements for making a pull request

Thank you for contributing to our project! 

Please fill out the template below to help the project maintainers review it as fast as possible and include your contribution to the project.

### What does it fix?

Closes #140 

Please mention the main changes this PR brings.

### How has it been tested?

Please describe the tests that you ran to verify your changes.

```bash
cd backend\src
```
```bash
docker-compose build frontend
```
```bash
docker-compose up
```
open http://localhost:5002
login 

>get redirected properly back

### CODE REVIEW

File: frontend/env.sh [hunk 1]
```diff
@@ -4,6 +4,9 @@
 rm -rf ./env-config.js
 touch ./env-config.js
 
+# add all env variables in .env file
+printenv > .env
```
Comment (surdu) [inline frontend/env.sh:8]: Don't we want to append (`>>`) to the `.env` file ?

**Review by RaduCStefanescu — APPROVED** [review]
